import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { readFile, writeFile, mkdir, cp, mkdtemp, rm } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { resolve, join, sep } from 'node:path';
import { tmpdir } from 'node:os';

const root = process.cwd(), host = resolve(root, '../Anas');
const require = createRequire(join(host, 'package.json'));
const { _electron: electron } = require('playwright');
const { expect } = require('playwright/test');
const { closeElectronTestApplication } = require('./scripts/electron-test-close.cjs');
const config = JSON.parse(await readFile(join(root, '.local/rdp-test.json'), 'utf8'));
let pin;
try {
  const trust = JSON.parse(await readFile(join(root, '.local/rdp-trust.json'), 'utf8'));
  if (trust.target_key === createHash('sha256').update(JSON.stringify([config.host, config.port ?? 3389])).digest('hex')) pin = trust.certificate_sha256;
} catch {}
if (!pin) {
  const data = JSON.parse(await readFile(resolve(process.env.HOME, '.galeAnas/plugins_data/rdp/profiles.json'), 'utf8'));
  pin = data.certificate_trust?.find(item => item.host === config.host && item.port === (config.port ?? 3389))?.sha256;
}
assert.ok(pin, 'A previously verified certificate is required.');
const directory = await mkdtemp(join(tmpdir(), 'anas-rdp-handoff-'));
let app, phase = 'prepare';
try {
  const pkg = join(directory, 'package');
  await mkdir(pkg);
  await build({ entryPoints: [join(root, 'src/ui/app.ts')], bundle: true, format: 'esm', platform: 'browser', outfile: join(pkg, 'app.js') });
  await build({ entryPoints: [join(root, 'src/backend.ts')], bundle: true, format: 'cjs', platform: 'node', outfile: join(pkg, 'backend.cjs') });
  for (const file of ['index.html', 'style.css']) await cp(join(root, 'src/ui', file), join(pkg, file));
  await cp(join(root, 'lang'), join(pkg, 'lang'), { recursive: true });
  await cp(join(root, 'assets'), join(pkg, 'assets'), { recursive: true });
  const native = join(pkg, 'native', process.platform + '-' + process.arch);
  await mkdir(native, { recursive: true });
  const binary = 'anas-rdp-session' + (process.platform === 'win32' ? '.exe' : '');
  await cp(join(root, 'dist/native', process.platform + '-' + process.arch, binary), join(native, binary));
  if (process.platform === 'darwin') execFileSync('codesign', ['--force', '--sign', '-', join(native, binary)], { stdio: 'ignore' });
  await writeFile(join(pkg, 'PLUGIN.json'), JSON.stringify({ version: 0, id: 'rdp', name: 'Remote Desktop', icon: 'assets/remote-desktop.svg', plugin_version: '0.1.6', api_version: 2, ui: 'index.html', backend: 'backend.cjs', lang: 'lang' }));
  await mkdir(join(directory, 'documents'));
  await writeFile(join(directory, 'package.json'), JSON.stringify({ name: 'anas-rdp-test', version: '1.0.0', main: 'main.cjs' }));
  await cp(join(host, 'data'), join(directory, 'data'), { recursive: true });
  await writeFile(join(directory, 'main.cjs'), `const {app,dialog}=require('electron'); app.setPath('documents',${JSON.stringify(join(directory, 'documents'))}); dialog.showErrorBox=()=>app.exit(1); require(${JSON.stringify(join(host, 'out/main/index.js'))});`);
  const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE; delete env.ELECTRON_RENDERER_URL;
  app = await electron.launch({ executablePath: require('electron'), args: [directory, '--data-dir', join(directory, 'data-profile')], cwd: host, env, timeout: 45000 });
  const main = await app.firstWindow();
  await main.locator('[data-agent-composer-input]').waitFor({ timeout: 45000 });
  await main.evaluate(() => gale.config.updateSettings({ language: 'en', theme: 'dark' }));
  await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, join(pkg, 'PLUGIN.json'));
  await main.evaluate(() => gale.plugins.install());
  const backend = (method, params) => main.evaluate(({ method, params }) => gale.plugins.invoke('rdp', 'backend.call', { method, params }), { method, params });
  phase = 'connect';
  const profile = await backend('profiles.save', { ...config, name: 'Handoff verification', passwordAction: 'set', openMode: 'sidebar', runInBackground: true });
  await backend('trusts.save', { host: config.host, port: config.port ?? 3389, sha256: pin });
  await backend('profiles.launch', { id: profile.id, revision: profile.revision });
  await main.evaluate(id => gale.plugins.invoke('rdp', 'host.openView', { instanceId: id, location: 'sidebar', title: 'Handoff verification' }), profile.id);
  const frameIn = page => page.frames().find(frame => frame.url().startsWith('anas-plugin://rdp/'));
  let frame = frameIn(main);
  await expect(frame.locator('#status')).toHaveText('Connected', { timeout: 40000 });
  const original = await backend('find', { owner: profile.id });
  assert.ok(original);
  const view = (await main.evaluate(() => gale.panels.list())).find(item => item.content.kind === 'plugin' && item.content.instanceId === profile.id);
  const colors = async page => {
    await expect.poll(() => frameIn(page).locator('canvas').evaluate(canvas => {
      const pixels = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data;
      const values = new Set(); for (let i = 0; i < pixels.length; i += 400) values.add(pixels[i] + ',' + pixels[i + 1] + ',' + pixels[i + 2]); return values.size;
    }), { timeout: 15000 }).toBeGreaterThan(4);
  };
  await colors(main);
  phase = 'transfer';
  for (let round = 0; round < 3; round++) {
    phase = `transfer round ${round + 1}`;
    await main.evaluate(id => gale.panels.move(id, 'window'), view.viewId);
    const target = app.context().pages().find(page => page.url().includes('panel-window.html'));
    await colors(target);
    await expect(target.getByRole('button', { name: 'Disconnect', exact: true })).toBeVisible();
    await target.getByRole('button', { name: 'Disconnect', exact: true }).hover();
    await expect(target.getByRole('tooltip')).toHaveText('Disconnect');
    await colors(target);
    assert.equal((await backend('find', { owner: profile.id })).id, original.id);
    await target.evaluate(() => { void panelWindow.moveToSidebar(); });
    await expect.poll(() => target.isClosed()).toBe(true);
    await colors(main);
  }
  phase = 'close-and-reattach';
  await frameIn(main).evaluate(id => { void anas.moveView({ instanceId: id, location: 'window' }); }, profile.id);
  await expect.poll(() => app.context().pages().some(page => page.url().includes('panel-window.html'))).toBe(true);
  const lastWindow = app.context().pages().find(page => page.url().includes('panel-window.html'));
  await expect.poll(() => !!frameIn(lastWindow)).toBe(true);
  await colors(lastWindow);
  await expect.poll(() => backend('profiles.get', { id: profile.id }).then(profile => profile.openMode)).toBe('window');
  await main.evaluate(id => gale.panels.close(id), view.viewId);
  await new Promise(resolve => setTimeout(resolve, 1000));
  assert.equal((await backend('find', { owner: profile.id })).id, original.id);
  const remembered = (await backend('runtime.state', {})).sessions.find(session => session.id === original.id);
  assert.equal(remembered.profile.openMode, 'window');
  await main.evaluate(({ id, location }) => gale.plugins.invoke('rdp', 'host.openView', { instanceId: id, location, title: 'Handoff verification' }), { id: profile.id, location: remembered.profile.openMode });
  const restoredWindow = app.context().pages().find(page => page.url().includes('panel-window.html'));
  await colors(restoredWindow);
  assert.equal((await backend('find', { owner: profile.id })).id, original.id);
  await restoredWindow.evaluate(() => { void panelWindow.moveToSidebar(); });
  await expect.poll(() => restoredWindow.isClosed()).toBe(true);
  await colors(main);
  phase = 'move-after-profile-deletion';
  const activeProfile = (await backend('profiles.list', {})).find(item => item.id === profile.id);
  await assert.rejects(backend('profiles.delete', { id: profile.id, revision: activeProfile.revision }), /RDP_PROFILE_ACTIVE/);
  const profileFile = join(directory, 'data-profile/plugins_data/rdp/profiles.json');
  const external = JSON.parse(await readFile(profileFile, 'utf8'));
  external.profiles = external.profiles.filter(item => item.id !== profile.id);
  await writeFile(profileFile, JSON.stringify(external));
  const reopened = (await main.evaluate(() => gale.panels.list())).find(item => item.content.instanceId === profile.id);
  await main.evaluate(id => gale.panels.move(id, 'window'), reopened.viewId);
  const movedWithoutProfile = app.context().pages().find(page => page.url().includes('panel-window.html'));
  await colors(movedWithoutProfile);
  assert.equal((await backend('find', { owner: profile.id })).id, original.id);
  await movedWithoutProfile.evaluate(() => { void panelWindow.moveToSidebar(); });
  await expect.poll(() => movedWithoutProfile.isClosed()).toBe(true);
  await colors(main);
  assert.equal((await backend('find', { owner: profile.id })).id, original.id);
  phase = 'disconnect';
  await frameIn(main).locator('#disconnect').click();
  await expect.poll(() => backend('find', { owner: profile.id })).toBe(null);
  await main.evaluate(id => gale.panels.close(id), reopened.viewId);
  phase = 'foreground-close';
  const foreground = await backend('profiles.save', { ...config, name: 'Foreground close verification', passwordAction: 'set' });
  assert.equal(foreground.runInBackground, false);
  await backend('profiles.launch', { id: foreground.id, revision: foreground.revision });
  await main.evaluate(id => gale.plugins.invoke('rdp', 'host.openView', { instanceId: id, location: 'sidebar' }), foreground.id);
  await expect.poll(() => !!frameIn(main)).toBe(true);
  await expect(frameIn(main).locator('#status')).toHaveText('Connected', { timeout: 40000 });
  const foregroundResource = await backend('find', { owner: foreground.id });
  await frameIn(main).evaluate(() => { void anas.moveView('window'); });
  await expect.poll(() => app.context().pages().some(page => page.url().includes('panel-window.html'))).toBe(true);
  const foregroundWindow = app.context().pages().find(page => page.url().includes('panel-window.html'));
  await expect.poll(() => !!frameIn(foregroundWindow)).toBe(true);
  await colors(foregroundWindow);
  assert.equal((await backend('find', { owner: foreground.id })).id, foregroundResource.id, 'Moving an opted-out desktop must preserve its connection.');
  await (await app.browserWindow(foregroundWindow)).evaluate(window => window.close());
  await expect.poll(() => foregroundWindow.isClosed()).toBe(true);
  await expect.poll(() => backend('find', { owner: foreground.id })).toBe(null);
  console.log('Host + RDP passed: round-trip moves, background close and same-session resume, deleted-profile handoff, explicit disconnect, and default foreground close ending a live RDP connection.');
} catch (error) {
  let message = String(error);
  for (const value of [config.host, config.username, config.password]) if (value) message = message.split(value).join('[redacted]');
  console.error('RDP host phase:', phase, message);
  process.exitCode = 1;
} finally {
  await closeElectronTestApplication(app);
  assert.ok(resolve(directory).startsWith(resolve(tmpdir()) + sep));
  await rm(directory, { recursive: true, force: true });
}
